<?php

namespace Tests\Unit\Models;

use PHPUnit\Framework\TestCase;
use App\Models\Tenant;
use App\Utils\Database;
use PDO;

/**
 * Testes unitários para o Model Tenant
 * 
 * Cenários cobertos:
 * - Criação de tenant
 * - Busca por API key
 * - Geração de API key única
 * - Validação de dados
 */
class TenantTest extends TestCase
{
    private PDO $testDb;
    private Tenant $tenantModel;

    protected function setUp(): void
    {
        parent::setUp();

        // Cria banco SQLite em memória
        $this->testDb = new PDO('sqlite::memory:');
        $this->testDb->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);

        // Cria tabela de tenants
        $this->testDb->exec("
            CREATE TABLE tenants (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name VARCHAR(255) NOT NULL,
                api_key VARCHAR(255) UNIQUE NOT NULL,
                status VARCHAR(50) DEFAULT 'active',
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ");

        // Cria modelo de teste com banco customizado
        $this->tenantModel = new Tenant();
        $reflection = new \ReflectionClass($this->tenantModel);
        $dbProperty = $reflection->getProperty('db');
        $dbProperty->setAccessible(true);
        $dbProperty->setValue($this->tenantModel, $this->testDb);
    }

    protected function tearDown(): void
    {
        parent::tearDown();
        // Limpa referências sem atribuir null a propriedades tipadas
        unset($this->testDb);
    }

    /**
     * Testa criação de tenant com API key gerada automaticamente
     */
    public function testCreateTenantWithAutoGeneratedApiKey(): void
    {
        // Arrange
        $name = 'Test Tenant';

        // Act
        $id = $this->tenantModel->create($name);

        // Assert
        $this->assertIsInt($id);
        $this->assertGreaterThan(0, $id);

        $tenant = $this->tenantModel->findById($id);
        $this->assertNotNull($tenant);
        $this->assertEquals($name, $tenant['name']);
        $this->assertNotEmpty($tenant['api_key']);
        $this->assertEquals('active', $tenant['status']);
        $this->assertEquals(64, strlen($tenant['api_key'])); // 32 bytes = 64 hex chars
    }

    /**
     * Testa criação de tenant com API key customizada
     */
    public function testCreateTenantWithCustomApiKey(): void
    {
        // Arrange
        $name = 'Test Tenant';
        $customApiKey = 'custom_api_key_123456789012345678901234567890123456789012345678901234567890';

        // Act
        $id = $this->tenantModel->create($name, $customApiKey);

        // Assert
        $tenant = $this->tenantModel->findById($id);
        $this->assertEquals($customApiKey, $tenant['api_key']);
    }

    /**
     * Testa busca de tenant por API key válida
     */
    public function testFindByApiKeyWithValidKey(): void
    {
        // Arrange
        $name = 'Test Tenant';
        $apiKey = 'test_api_key_123456789012345678901234567890123456789012345678901234567890';
        $id = $this->tenantModel->create($name, $apiKey);

        // Act
        $tenant = $this->tenantModel->findByApiKey($apiKey);

        // Assert
        $this->assertNotNull($tenant);
        $this->assertEquals($id, $tenant['id']);
        $this->assertEquals($name, $tenant['name']);
        $this->assertEquals($apiKey, $tenant['api_key']);
    }

    /**
     * Testa busca de tenant por API key inexistente
     */
    public function testFindByApiKeyWithInvalidKey(): void
    {
        // Arrange
        $invalidApiKey = 'invalid_api_key_123456789012345678901234567890123456789012345678901234567890';

        // Act
        $tenant = $this->tenantModel->findByApiKey($invalidApiKey);

        // Assert
        $this->assertNull($tenant);
    }

    /**
     * Testa geração de API keys únicas
     */
    public function testGenerateApiKeyUniqueness(): void
    {
        // Act
        $apiKey1 = $this->tenantModel->generateApiKey();
        $apiKey2 = $this->tenantModel->generateApiKey();

        // Assert
        $this->assertNotEquals($apiKey1, $apiKey2);
        $this->assertEquals(64, strlen($apiKey1));
        $this->assertEquals(64, strlen($apiKey2));
        $this->assertMatchesRegularExpression('/^[a-f0-9]{64}$/', $apiKey1);
        $this->assertMatchesRegularExpression('/^[a-f0-9]{64}$/', $apiKey2);
    }

    /**
     * Testa criação de múltiplos tenants
     */
    public function testCreateMultipleTenants(): void
    {
        // Arrange & Act
        $id1 = $this->tenantModel->create('Tenant 1');
        $id2 = $this->tenantModel->create('Tenant 2');
        $id3 = $this->tenantModel->create('Tenant 3');

        // Assert
        $this->assertNotEquals($id1, $id2);
        $this->assertNotEquals($id2, $id3);
        $this->assertNotEquals($id1, $id3);

        $allTenants = $this->tenantModel->findAll();
        $this->assertCount(3, $allTenants);
    }

    /**
     * Testa que API keys geradas são diferentes para cada tenant
     */
    public function testApiKeysAreUniquePerTenant(): void
    {
        // Arrange & Act
        $id1 = $this->tenantModel->create('Tenant 1');
        $id2 = $this->tenantModel->create('Tenant 2');

        $tenant1 = $this->tenantModel->findById($id1);
        $tenant2 = $this->tenantModel->findById($id2);

        // Assert
        $this->assertNotEquals($tenant1['api_key'], $tenant2['api_key']);
    }

    /**
     * Testa busca de tenant por ID
     */
    public function testFindById(): void
    {
        // Arrange
        $name = 'Test Tenant';
        $id = $this->tenantModel->create($name);

        // Act
        $tenant = $this->tenantModel->findById($id);

        // Assert
        $this->assertNotNull($tenant);
        $this->assertEquals($id, $tenant['id']);
        $this->assertEquals($name, $tenant['name']);
    }

    /**
     * Testa busca de tenant por ID inexistente
     */
    public function testFindByIdWithInvalidId(): void
    {
        // Act
        $tenant = $this->tenantModel->findById(99999);

        // Assert
        $this->assertNull($tenant);
    }

    /**
     * Testa atualização de tenant
     */
    public function testUpdateTenant(): void
    {
        // Arrange
        $id = $this->tenantModel->create('Original Name');
        $newName = 'Updated Name';

        // Act
        $updated = $this->tenantModel->update($id, ['name' => $newName]);

        // Assert
        $this->assertTrue($updated);
        $tenant = $this->tenantModel->findById($id);
        $this->assertEquals($newName, $tenant['name']);
    }

    /**
     * Testa atualização de status do tenant
     */
    public function testUpdateTenantStatus(): void
    {
        // Arrange
        $id = $this->tenantModel->create('Test Tenant');

        // Act
        $updated = $this->tenantModel->update($id, ['status' => 'inactive']);

        // Assert
        $this->assertTrue($updated);
        $tenant = $this->tenantModel->findById($id);
        $this->assertEquals('inactive', $tenant['status']);
    }

    /**
     * Testa exclusão de tenant
     */
    public function testDeleteTenant(): void
    {
        // Arrange
        $id = $this->tenantModel->create('Test Tenant');

        // Act
        $deleted = $this->tenantModel->delete($id);

        // Assert
        $this->assertTrue($deleted);
        $tenant = $this->tenantModel->findById($id);
        $this->assertNull($tenant);
    }
}

